### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.decoratedNode" is null

### ISSUE THREAD

**Issue by Ramona2022** [effad/ValidatorFX#29]
i believe i found 2 issues which will be fixed with one fix 

1. 

validator.createCheck()
	.withMethod(this::check)
	.dependsOn("combo", combo.isEmptyProperty())
	.decorates(combo.getValidationNode())	
	.immediate()
;
will throw 

java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.decoratedNode" is null
	at net.synedra.validatorfx.GraphicDecoration.layoutGraphic(GraphicDecoration.java:147)
	at net.synedra.validatorfx.GraphicDecoration.lambda$new$0(GraphicDecoration.java:56)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:101)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.scene.Parent.setLayoutFlag(Parent.java:930)
	at javafx.scene.Parent.layout(Parent.java:1190)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Scene.doLayoutPass(Scene.java:592)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2512)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:407)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:406)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)

2.  i want to invalidate a button with a message, but not decorate a node... some nullpointer ist thrown:
		validator.createCheck()
			.withMethod(this::checl)
			.dependsOn("field", field.isEmptyProperty())
			.immediate()
		; 
(my form is valid (save button ist enabled), but one button is disabled, because it is only enabled if a fieldvalue is set.)

Codeexample will follow. I think there should be the possibility that .decorates(Node)  is null, without throwing a Nullpointer

**Comment by Ramona2022** [comment]
I'm very sorry, this is not an issue in your code but mine. It is possible to use the validator without 
.decorates
My page/form/field/validator initialisation was wrong. After fixing it i don't receive the NullPointerException anymore.

**Comment by effad** [comment]
Closing the issue, since it is not a real issue :-).
