### ISSUE TITLE
Flaky test error CheckTest.testTextFieldMaxLength

### ISSUE THREAD

**Issue by effad** [effad/ValidatorFX#39]
This test fails **sometimes**, like this:
org.opentest4j.AssertionFailedError: expected: <Too long> but was: <Pretty long>
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at app//net.synedra.validatorfx.CheckTest.checkMessage(CheckTest.java:158)
	at app//net.synedra.validatorfx.CheckTest.testTextFieldMaxLength(CheckTest.java:142)

**Comment by effad** [comment]
Tried this on the command line: 
```
for i in `seq 1 10`; do ./gradlew cleanTest test; done
```
and got 6 FILED and 4 SUCCESSFUL runs.

**Comment by effad** [comment]
This seems to be a direct regression from the fix for Issue #38.

**Comment by effad** [comment]
FIX: As stated in WeakChangeListener we have to keep a reference to the ChangeListener passed into the WeakChangeListener.
