### ISSUE TITLE
NPE when working with target nodes that do not (yet) have a scene

### ISSUE THREAD

**Issue by effad** [effad/ValidatorFX#7]
Stack-Trace:
```
Caused by: java.lang.NullPointerException
	at net.synedra.validatorfx.GraphicDecoration.ensureStack(GraphicDecoration.java:76)
	at net.synedra.validatorfx.GraphicDecoration.add(GraphicDecoration.java:56)
	at net.synedra.validatorfx.Check.recheck(Check.java:111)
	at net.synedra.validatorfx.Check.lambda$new$0(Check.java:63)
...
```

**Comment by effad** [comment]
Fix: If target does not have a scene at the moment, we wait until it is added to one (by means of a listener). Once it has a scene, we setup the stack as required.
